---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Ciberseguridad Feminista Auto-Gestionada"
keywords:    "Seguridad, privacidad, feminista, guía, acoso, troll"
description: "Una guía auto-gestiva y super accesible, para que lxs feministas, activistas, y amiguxs tomen control de sus espacios digitales."
source_link: "https://github.com/Intimaria/DIY-Feminist-Cybersecurity-ES"
favicon:     "img/favicon.ico"
touch_icon:  ##"img/apple-touch-icon.png"
google_analytics_key: "UA-32315541-3"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

  exclude: [vendor]
